# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.IntegerField(db_index=True, null=True, unique=True)),
                ('title', models.TextField()),
                ('authors', models.TextField()),
                ('date', models.DateField()),
                ('journal', models.TextField()),
                ('volume', models.TextField(blank=True, null=True)),
                ('pages', models.TextField(blank=True, null=True)),
                ('issue', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
